language: rust
sudo: false
matrix:
  include:
    - rust: stable
      env:
        - NOTEST=1
    - rust: nightly
branches:
  only:
    - master
script:
  - |
      cargo build --verbose --features "$FEATURES" &&
      ([ "$NOTEST" = 1] || cargo test --verbose --features "$FEATURES")
